/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goldengymclub;

import goldengymclub.database.Database;
import goldengymclub.util.Deluxe;
import goldengymclub.util.Member;
import goldengymclub.util.NonDeluxe;
import javax.swing.JOptionPane;

/**
 *
 * @author Neoh
 */
public class EditMemberDetails extends javax.swing.JFrame {

    /**
     * Creates new form EditMemberDetails
     */
    
    
    private static Member member = null;
    
    public EditMemberDetails(Member member) {
        initComponents();
        
        this.member = member;
        
        txt_memberid.setText(member.getMember_id());
        txt_fullname.setText(member.getFirstname() + " " + member.getLastname());
        txt_email.setText(member.getEmail());
        txt_phone.setText(member.getPhone());
        
        if(member.getMembership() instanceof Deluxe){
            rb_deluxe.setSelected(true);
        } else if(member.getMembership() instanceof NonDeluxe){
            rb_nondeluxe.setSelected(true);
        } else {
            rb_weekday.setSelected(true);
        }
        
    }
    
    public void saveChangesToText(Member member){
        boolean success = Database.getInstance().modifyMember(member);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rb_deluxe = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rb_nondeluxe = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rb_weekday = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_memberid = new javax.swing.JLabel();
        txt_fullname = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        txt_email = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Member ID :");

        jLabel3.setText("Full Name :");

        rb_deluxe.setText("Deluxe");
        rb_deluxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_deluxeActionPerformed(evt);
            }
        });

        jLabel4.setText("Phone :");

        rb_nondeluxe.setText("Non-Deluxe");
        rb_nondeluxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_nondeluxeActionPerformed(evt);
            }
        });

        jLabel5.setText("Email :");

        rb_weekday.setText("Week-Day");
        rb_weekday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_weekdayActionPerformed(evt);
            }
        });

        jLabel6.setText("Select type of membership :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Edit Member Details");

        txt_memberid.setText("Member ID");

        txt_fullname.setText("Member Full Name");

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_save.setText("Save Changes");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(txt_memberid))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_fullname)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_save)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_cancel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb_deluxe)
                                .addGap(18, 18, 18)
                                .addComponent(rb_nondeluxe)
                                .addGap(18, 18, 18)
                                .addComponent(rb_weekday))
                            .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_memberid)
                    .addComponent(txt_fullname))
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_deluxe)
                    .addComponent(rb_nondeluxe)
                    .addComponent(rb_weekday))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel)
                    .addComponent(btn_save))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rb_deluxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_deluxeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rb_deluxeActionPerformed

    private void rb_nondeluxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_nondeluxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_nondeluxeActionPerformed

    private void rb_weekdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_weekdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_weekdayActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        
        String email = txt_email.getText().toString();
        String phone = txt_phone.getText().toString();
        
        String membership = null;
        
        if(rb_deluxe.isSelected()){
        }
        else if(rb_nondeluxe.isSelected()){
        }
        else if(rb_weekday.isSelected()){
        }
        
        member.setEmail(email);
        member.setPhone(phone);
        //member.setMembership(membership);
       
        saveChangesToText(member);
        
        JOptionPane.showMessageDialog(null, "Changes saved!");
        this.dispose();
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMemberDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMemberDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMemberDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMemberDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditMemberDetails(member).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rb_deluxe;
    private javax.swing.JRadioButton rb_nondeluxe;
    private javax.swing.JRadioButton rb_weekday;
    private javax.swing.JTextField txt_email;
    private javax.swing.JLabel txt_fullname;
    private javax.swing.JLabel txt_memberid;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
